### ISSUE TITLE
Setting an exported type inside of a type parameter causes error

### ISSUE THREAD

**Issue by Nickuhhh** [Kampfkarren/full-moon#100]
![image](https://user-images.githubusercontent.com/25470747/97660481-15c2fd80-1a48-11eb-8133-b0ded69be08a.png)

foo is defined as a required module and bar is an exported type inside of that module.

**Comment by JohnnyMorganz** [comment]
This seems to be parsed fine on latest full_moon (0.7.0) and selene - are you sure that your selene extension was up to date?

**Comment by Kampfkarren** [comment]
I'll take your word for it 😛
