### ISSUE TITLE
Invalid parsing for conditional iterators

### ISSUE THREAD

**Issue by OverHash** [Kampfkarren/full-moon#105]
Full moon currently parses the following code as valid:
```lua
local d = true
for _, v in d and pairs({}) or pairs({}) do

end
```

This code will in fact error.
```
invalid argument #1 (table expected, got nil)
```
Full moon should also error in this case.

**Comment by Kampfkarren** [comment]
I misunderstood. Lua parses this, full-moon parses this, so this is not a bug. It's just hideous.
