### ISSUE TITLE
Parsing fails on files with BOM

### ISSUE THREAD

**Issue by Stanzilla** [Kampfkarren/full-moon#117]
I just tried parsing a few files with Selene that had a UTF8 BOM and it failed to parse them, the error was pretty generic, should full-moon work with BOM or should the error point out BOM and tell users to remove it?

**Comment by Kampfkarren** [comment]
Can you share the error you got?

Whether or not full-moon SHOULD support them is the same as whether Lua does, whatever that answer is.

**Comment by Stanzilla** [comment]
`ERROR: Error parsing x.lua: error occurred while tokenizing: unexpected character ﻿ at line 1, column 1`

**Comment by Kampfkarren** [comment]
Does PUC-Rio Lua parse that?

**Comment by Stanzilla** [comment]
Looks like it, yeah. Tested it with 5.3.3 on Linux.
