### ISSUE TITLE
Start position of tokens at the beginning of the line are recorded as being at the end of the previous line.

### ISSUE THREAD

**Issue by tomprince** [Kampfkarren/full-moon#128]
I was experimenting with using [nom_locate](https://github.com/fflorent/nom_locate/) for tracking source positions. I've got a mostly working branch with that, but I discovered that it generates different source positions in a number of places:
- any token at the beginning of the line currently has its position as being at the end of the previous line
- a whitespace token consisting of a single new line has start and end position with the same line and column, on the previous line

I think either decision for the second difference could be argued to be correct, but I think the first one is definitely an error. I've got a patch to make the first change (and am working on updating the tests), but I'm wondering if the second change also wants to be made.

**Comment by tomprince** [comment]
I guess a third case (somewhat) is whether the eof after a trailing newline should be marked as being on a new line. I'm inclined to argue yes in the case.

**Comment by Kampfkarren** [comment]
> any token at the beginning of the line currently has its position as being at the end of the previous line

Can you provide an example of this? It's a bit hard to visualize in my head.

> a whitespace token consisting of a single new line has start and end position with the same line and column, on the previous line

As you pointed out in #125, I believe this is just a consequence of the choice made to prioritize trivia.

**Comment by tomprince** [comment]
> > any token at the beginning of the line currently has its position as being at the end of the previous line
> 
> Can you provide an example of this? It's a bit hard to visualize in my head.

For example. in 
```
do
end
````
the `end` token has a start position at the end of the first line.


> > a whitespace token consisting of a single new line has start and end position with the same line and column, on the previous line
> 
> As you pointed out in #125, I believe this is just a consequence of the choice made to prioritize trivia.

It isn't clear to me that that is the case, as having the start position being on the previous line doesn't match with the tokens being associated with the following trivia. In any case, it only happens for tokens that are exactly `\n`.
