### ISSUE TITLE
Kill the `Cow`s and lifetimes

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/full-moon#129]
From what I've heard from other developers trying to use full-moon (Dreamcraft), the lifetime juggling everywhere is a big mess. I can attest to the same with Selene. It leads to a lot of weird code like matching `&*node` and such, and is just generally confusing.

The motivation behind `<'ast>` was that full-moon should be able to borrow from the string provided. Furthermore, the `Cow`s are necessary in order to allow both borrowed (from the string) and owned (created from mutation).

However, this is not the way it works right now. I could never get borrowed to work, so it just ends up cloning everything anyway, and in really awful news, it led to an `unsafe` being created in order to get the dang thing to work. While it's likely both these issues are solvable, this compounded with the hard to use API means I would rather just kill 'ast and the Cows.

Instead, full-moon will simply just own everything it has, and not try to bother borrowing.

**Comment by tomprince** [comment]
Looking at the code, the only place where `Ast.tokens` field is used is for access to the EOF token, so there is no reason post-parse, to not keep the tokens (or [parts of them](https://github.com/Kampfkarren/full-moon/issues/23#issuecomment-799652220)) directly in the ast.

---

The one reason we might not want to do that during parsing, we copy `TokenReference`s a bunch when backtracking. One idea I had (though it conflicts with my suggestions in #23) was to parameterize all the ast nodes with the type of token, which could then be `Token<'text>` or `TokenReference<'text>` or `Cow<'parse, TokenReference<'text>>` and we could use the last during parsing, and return one of the former two depending on the use-case.

Given my suggestion in #23, another thought I had is storing trivia as a pair of (wrapped) `Cow<'text, str>`s, and reparsing as required. This would make trivia cheap to copy during parsing, at the cost of making manipulating it more expensive to manipulate them later. Or we could maybe use a [smallvec](https://docs.rs/smallvec) of leading and trailing trivia.

----

All that being said, if performance is adequate right now, with copying everything always with `Vec`s of trivia, maybe it isn't worth worrying about this kind of optimization right now.

**Comment by Kampfkarren** [comment]
Like I said before, I can't remember the motivation behind the tokens field in general other than that I wanted to make `print` implemented as just iterating over every token in the vector and printing it. That ship has sailed.

**Comment by tomprince** [comment]
Thinking about this a little bit more, removing the `Cow<'_, TokenReference<'_>>` but not the `Cow<'_, str>` would be an easy ergonomics win at the cost of a breaking change in a way that is likely to be broken again by the suggestions I made in #23. I was initially disinclined to immediately make this breaking change now, to avoid churn, but I realized that I don't know how tolerable breaking changes are for this project. This particular change is probably mostly mechanical to address.

**Comment by Kampfkarren** [comment]
We're going 1.0.0 soon (basically, just whenever I get around to pushing the release), but breaking changes are fine--Roblox forces us to make a lot of them anyway, due to how often their custom Lua build changes (which makes me want to see if I can put those types in another repository, but eh).
