### ISSUE TITLE
Make the parser error tolerant

### ISSUE THREAD

**Issue by Dekkonot** [Kampfkarren/full-moon#170]
I'm surprised that this isn't an existing issue given that there's on-going discussion about it on Discord, but here we go.

In order for full-moon to be used for a language server, it must recover from errors. This is commonly referred to as error recovery or an 'error tolerant' parser.

As a benefit, this would let projects like Selene and StyLua diagnose or fix syntax errors (what comes to mind is something like `=` instead of `==` in an expression or `(a, b, c,)` in a function fall). It would *also* make the parser not break entirely whenever Roblox introduced new syntax, which is a good thing. :wink:

Given the benefits and potential uses, it should probably be a priority and a requirement before we reach 1.0.

**Comment by Kampfkarren** [comment]
Requirement before 1.0 is a bit much IMHO--my goals for 1.0 was solid immutable and mutable parsing, which we're just about finished with, save some API quirks. I think this is a fine candidate for 2.0, though.

**Comment by Dekkonot** [comment]
I feel it would be a mistake to push full-moon to 1.0 without it but if you feel differently I'll follow your lead. My logic was that most of the utility of parsing Luau specifically is in making tools for it, and this is one of the Big Ones for making tools more viable (the other one is incremental parsing, but that's a whole new fan or worms).
