### ISSUE TITLE
support type intersection syntax

### ISSUE THREAD

**Issue by matthargett** [Kampfkarren/full-moon#176]
```
function GError.new(
        message: string,
        originalError: (Error & { extensions: any? }), -- new syntax
        extensions: { [string]: any }? 
): GError
```

Simple solution: Anywhere a `|` can be used in a typedef can also be an `&`

**Comment by Kampfkarren** [comment]
1. This is intersection, not union.
2. We already support this on the latest master, either StyLua is not updated or there's something else going on here, I suspect the `?`.
