### ISSUE TITLE
support generic functions feature of Luau

### ISSUE THREAD

**Issue by matthargett** [Kampfkarren/full-moon#179]
Documented here:
https://luau-lang.org/typecheck#generic-functions

Here's the specific code that full-moon won't currently parse:
```lua
type Resource<I, V> = {
   read: (I) -> V,
}

type Suspender = {
    andThen: (() -> any, () -> any) -> any
}

type PendingResult = {
    status: number,
    value: Suspender,
}

type ResolvedResult<V> = {
    status: number,
    value: V,
}

type RejectedResult = {
   status: number,
   value: any,
}

type Result<V> = PendingResult | ResolvedResult<V> | RejectedResult

local Pending = 0

local exports = {}

local function identityHashFn(input)
	return input
end

local function accessResult(
   resource: any,
   fetch: (I) -> Thenable<V, any>,
   input: I,
   key: K
): Result<V>
  return {
	status = Pending,
	value = { andThen = function(x) x() end }
  }
end

exports.unstable_createResource = function<I, K, V>(
   fetch: (I) -> Thenable<V, any>,
   maybeHashInput: ((I) -> K)?
): Resource<I, V>
    local hashInput: (any) -> any
    if maybeHashInput ~= nil then
        hashInput = (maybeHashInput :: (any) -> any)
    else
        hashInput = identityHashFn :: any
    end

    local resource
    resource = {
            read = function(input: I): V
		local key = hashInput(input)
                local result: Result<V> = accessResult(resource, fetch, input, key)
                if result.status == Pending then
                    local suspender = result.value
                    error(suspender)
	        end
                local value = result.value
                return value
	    end
    }
   return resource
end

return exports
```

**Comment by Kampfkarren** [comment]
@JohnnyMorganz pointed out that this is ambiguous:

```lua
return f<x, y>(g)
```

As this could be calling `f(g)` with generics `<x, y>`, or it could be `return f < x, y > g`. Does Luau just report this as ambiguous and not parse it? I'd expect not since it's so concerned about backwards compatibility.

**Comment by Kampfkarren** [comment]
Oh, maybe `f<...>(g)` just isn't valid syntax at all, I don't see it in that paper.

**Comment by andyfriesen** [comment]
We don't have any plans to support explicitly supplying generic parameters at function call sites.

It's never going to be the case that actual execution flow is decided by the generic parameters, so it should be fine to always allow type inference to deduce what the generic parameters ought to be.

If that isn't sufficient, you can use a temporary and a type assertion.

```lua
function f<T>(a: T, b: T): string
    ...
end

local f_: (number, number) -> string = f
local result = f_(5, 6)
```

**Comment by matthargett** [comment]
Luau doesn't do any kind of type directed dispatch, so it isn't necessary to explicitly supply generic parameters.

**Comment by andyfriesen** [comment]
Luau does not offer syntax for this kind of function call.

If we ever actually did come across a compelling use case for it, we would introduce unambiguous syntax. (maybe take a cue from Rust?  `foo::<number>(bar)`)

**Comment by Kampfkarren** [comment]
That's good news, and yeah--turbofish would be perfectly fine for us, since I don't think it increases complexity.
