### ISSUE TITLE
don't fail to parse with multiple return values from a modules

### ISSUE THREAD

**Issue by matthargett** [Kampfkarren/full-moon#189]
full-moon throws a parse error when trying to parse a file that returns multiple values. while this is a bug in the code, the AST should still produce for higher-level tools to warn/error about the bug.

```lua
local Foo = require(script.Parent.Parent.Foo)

return Foo.bar

return {}
```

**Comment by Kampfkarren** [comment]
This sounds like it'd be covered in #170, but is not something we should have until we have a real error tolerance model.

**Comment by Kampfkarren** [comment]
To clarify, this is because full-moon should not be producing an AST if the Lua syntax itself is not valid.
