### ISSUE TITLE
Luau generic functions

### ISSUE THREAD

**Issue by freddylist** [Kampfkarren/full-moon#197]
Luau has re-enabled [generic functions](https://luau-lang.org/typecheck#generic-functions), but I get a parsing error when I try to use them.

I filed an [issue](https://github.com/Kampfkarren/selene/issues/304) in the Selene repo with details.

**Comment by JohnnyMorganz** [comment]
I thought I added this in #181, but I realise that I didn't do it for callback types, just for an actual function declaration.
