### ISSUE TITLE
add 'meta' field for node 

### ISSUE THREAD

**Issue by attliaLin** [Kampfkarren/full-moon#212]
Hi! I'm implementing a `Lua` analayzer with full_moon. I want to store some external information in the nodes but it's hard with Visitor or VisitorMut. 

Maybe it's good to add a `id` (auto add, for easy to search in other information visitor) or `meta` field with [Value](https://docs.serde.rs/serde_json/value/enum.Value.html) in the node for external information.

**Comment by JohnnyMorganz** [comment]
I think it would definitely be nice to have some sort of identifier for each specific node, and then you can externally tag data for a specific identifier (rustc also has something similar: https://rustc-dev-guide.rust-lang.org/identifiers.html) - a `meta` field doesn't seem as great. 

In the meantime though, a workaround is to use the [span](https://docs.rs/full_moon/0.14.0/full_moon/node/trait.Node.html#method.range) of a Node, and map data to a specific span. You can't lookup a specific node from a span, but if you have the node already and you just want relevant data for it, this works. I know [selene has an example of this](https://github.com/Kampfkarren/selene/blob/main/selene-lib/src/ast_util/scopes.rs)

**Comment by Kampfkarren** [comment]
Definitely can't be added per node without either increasing memory usage even for non-consumers, or without adding a generic to every single possible node (I need to do this eventually for plugin support) so that it can just default to a ZST like ().

The range is kinda the best hack for this so far, unfortunately.

**Comment by attliaLin** [comment]
Yeah, I will try to hack with it. Thank you all!

While I think we can still provide it with some feature like `features = ["identifier"]` for someone who don't care about memory‘s increase.
