### ISSUE TITLE
[feature request] lua 5.3 support

### ISSUE THREAD

**Issue by sanga** [Kampfkarren/full-moon#221]
What are the chances of adding support for lua 5.3? This seems fairly presumptuous on my part so fair enough if you close this.

**Comment by Kampfkarren** [comment]
I can't remember, what syntax was added in Lua 5.3? I thought it's big feature was integers, which I don't think matter on a syntax level.

**Comment by sanga** [comment]
Sorry just now I don't have time but to post this link. https://www.lua.org/manual/5.3/manual.html#8 but at least I'd guess bitwise operators and I'm '~' also.

**Comment by Kampfkarren** [comment]
Bitwise ops, that's what it was, thanks!

**Comment by sanga** [comment]
Thank you! Btw, presumably the repo subtitle "A lossless Lua 5.1 parser" is now slightly incorrect?

**Comment by Kampfkarren** [comment]
It's been slightly incorrect for a bit 😅
