### ISSUE TITLE
[feature request] local variable attributes (Lua 5.4)

### ISSUE THREAD

**Issue by will** [Kampfkarren/full-moon#232]
Lua 5.4 added support for `<const>` and `<close>` as attributes to local variables. I think just those two. https://www.lua.org/manual/5.4/manual.html#3.3.7

And it looks in usage like

```lua
local foo <const> = 3
```

Would you consider adding support for these? Even if the other 5.3 or 5.4 features aren't there, just this one would be useful for me.

**Comment by Kampfkarren** [comment]
We can because it's forwards compatible, though ideally we get the ability to toggle Lua versions first.
