### ISSUE TITLE
0.16 fails to parse comments, escaped multi line strings

### ISSUE THREAD

**Issue by matthargett** [Kampfkarren/full-moon#241]
A few examples that fail to parse in stylua 0.15, but were fine in stylua 0.14.3:
```
function stringify(value: any): string
        if _G.__DEV__ then
                return ([=[[%s]]=]):format(Array.join(
                ))
        end
        return ([[{%s}]]):format(Array.join(
                Array.map(entries, function(entry)
                        return ([["%s":%s]]):format(entry[1], entry[2])
                end),
                ","
        ))
end
```

```
--[Common IPAs]--
```

and

```
--( xyz doesn't abc )
```

**Comment by napei** [comment]
![image](https://user-images.githubusercontent.com/8946502/191658135-e42a28f2-2b92-471f-921c-a4ea349df871.png)
I'll add to this, commenting *some* elements of a table is another one. Reckons it's an "unclosed comment"

**Comment by Kampfkarren** [comment]
Yeah, `--[` and `--(` currently break the parser.

**Comment by Kampfkarren** [comment]
I should have this fixed tonight.
