### ISSUE TITLE
Support instanced generic types with no parameters

### ISSUE THREAD

**Issue by goldenstein64** [Kampfkarren/full-moon#246]
Although it is illegal to declare a generic type with no parameters,

```lua
-- Luau: SyntaxError: Expected identifier, got '>'
type Foo<> = () -> ()
```

it *is* legal to declare a generic type with a type pack parameter and instance it with no arguments. Full Moon can't parse this.

```lua
type Foo<T...> = (T...) -> ()

-- this creates '() -> ()'
type Bar = Foo<>
```

Note that this is illegal.

```lua
-- Luau: TypeError: Type parameter list is required
type Bar = Foo
```

I came across this issue when formatting with StyLua, so if it's actually a StyLua issue, let me know.

**Comment by JohnnyMorganz** [comment]
Looks like it should just be a case of changing this from `OneOrMore` to `ZeroOrMore`
https://github.com/Kampfkarren/full-moon/blob/7a6afa17669aba856245ae3c0ea62f580466ee82/full-moon/src/ast/parsers.rs#L1673
