### ISSUE TITLE
Support LuaJIT number notations (floating point, number suffixes)

### ISSUE THREAD

**Issue by Duckwhale** [Kampfkarren/full-moon#255]
See https://github.com/JohnnyMorganz/StyLua/issues/621 :)

---

Example:

```lua
local num = 0x1p-1026
num = 0x1.5p-3
```

---

These are supported in LuaJIT and in fact used in its own Lua modules, e.g. [here](https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/jit/dump.lua#L335). Trying to format them results in a parser error:

![image](https://user-images.githubusercontent.com/16489133/203593951-b7db269f-42aa-4bf8-bcb8-5954152eb7f7.png)

---

More information about the extension:

> tonumber() etc. use builtin string to number conversion
>
> All string-to-number conversions consistently convert integer and floating-point inputs in decimal and hexadecimal on all platforms. strtod() is not used anymore, which avoids numerous problems with poor C library implementations. The builtin conversion function provides full precision according to the IEEE-754 standard, it works independently of the current locale and it supports hex floating-point numbers (e.g. 0x1.5p-3). 

Source: [https://luajit.org/extensions.html](https://luajit.org/extensions.html)

**Comment by Kampfkarren** [comment]
Can you copy and paste the issue details here as well?

**Comment by Duckwhale** [comment]
Sure. Done!

**Comment by JohnnyMorganz** [comment]
Should probably also support `LL` and `ULL` number suffixes (looks like its case insensitive), and complex numbers `12.5i`

**Comment by JohnnyMorganz** [comment]
Fixed in https://github.com/Kampfkarren/full-moon/pull/258

**Comment by Duckwhale** [comment]
Thank you!
