### ISSUE TITLE
feat: add a recovering parser

### ISSUE THREAD

**Issue by SkyfallWasTaken** [Kampfkarren/full-moon#259]
From what I can tell, Full Moon has no way to try and find more errors or make a partial AST because of errors.

I think that a recovering parser would be useful so that library users can at least do _some_ work with a partial AST instead of not being able to do anything.

**Comment by Kampfkarren** [comment]
https://github.com/Kampfkarren/full-moon/issues/170

It's a huge ask but something I have plans for in a rewrite
