### ISSUE TITLE
Support instanced namespaced generic types with no parameters

### ISSUE THREAD

**Issue by goldenstein64** [Kampfkarren/full-moon#275]
Similar issue to #246, I didn't comment on it because I thought the fix wasn't pushed for the longest time.

It's legal to declare a generic type with a type pack parameter and instance it with no arguments.

```lua
type Foo<T...> = (T...) -> ()

-- this creates '() -> ()'
type Bar = Foo<>
```

But it's also legal to import a generic type with a type pack parameter from another module and instance that with no arguments. Full Moon can't parse this.

```lua
-- module.lua
export type Foo<T...> = (T...) -> ()

return nil
```
```lua
-- init.lua
local module = require(script.module)

-- this creates '() -> ()'
type Bar = module.Foo<>
```

**Comment by Kampfkarren** [comment]
What is https://github.com/Kampfkarren/full-moon/blob/83589cc4f1526352dc34f19b32936af009877f54/full-moon/tests/roblox_cases/pass/types_generic_no_parameters/source.lua testing if not this? What error are you getting in what version of what tool?

**Comment by Kampfkarren** [comment]
Oh, X.Y<> specifically didn't parse?

**Comment by goldenstein64** [comment]
Yes, precisely that.

And I got that error from the latest version of StyLua, which was using Full Moon v0.18.1

**Comment by JohnnyMorganz** [comment]
This is fixed in the parser rewrite. I have added a test case for this
