### ISSUE TITLE
Parsing errors for variadic types in generic type

### ISSUE THREAD

**Issue by jeparlefrancais** [Kampfkarren/full-moon#285]
I'm working on getting Luau types into [darklua](https://github.com/seaofvoices/darklua) and I encountered a few issues with how full-moons parses variadic types.

Just to avoid confusion, I'm referring to variadic types as the `VariadicTypePack` entry in the grammar:
```
VariadicTypePack = '...' Type
```

When they're used in a generic type (like `Name<...VariadicType>`), it seems like full-moon does not parse the variadic type properly and requires that `VariadicType` should be a name, where it could be any type value.

This should be valid but it generates a parser error:
```lua
type T = Fn<...'ok'>
```

**Comment by JohnnyMorganz** [comment]
This is fixed in the parser rewrite. I have added a test case for this
