### ISSUE TITLE
Unable to parse intersection with `typeof` (rc5)

### ISSUE THREAD

**Issue by jeparlefrancais** [Kampfkarren/full-moon#314]
I found this issue with full-moon rc5, where intersection types using typeof don't parse:

```lua
export type Expect = typeof({}) & string
```

Which comes up in jest for example: https://github.com/jsdotlua/jest-lua/blob/main/src/expect/src/types.lua#L406-L408

**Comment by YetAnotherClown** [comment]
It looks like the minimal repro provided is actually incorrect, it does parse. The issue appears in the Jest example, specifically having `typeof()` on a newline.

A proper minimal repro would be:
```luau
export type T =
    typeof({})
```
