### ISSUE TITLE
Sometimes parser is quite slow

### ISSUE THREAD

**Issue by tversteeg** [Kampfkarren/full-moon#49]
Parsing the following file took me 15 seconds to get the tokens and 41 seconds to convert the tokens into an AST: https://github.com/Tieske/date/blob/master/src/date.lua

**Comment by Kampfkarren** [comment]
Thanks for the repro case--I'll try to profile this and see what results I get.

**Comment by tversteeg** [comment]
A suggestion: wouldn't it be better to use something like [nom](https://github.com/Geal/nom) or another parser-* system instead of regex since the performance of regex is quite bad in Rust?

**Comment by Kampfkarren** [comment]
I've never worked with nom, but you can take a crack at that if you want. 😃

**Comment by tversteeg** [comment]
I've made a small attempt to replace `advance_identifier` with a nom counterpart (#51). Most tests seem to succeed but not all of them, I also can't run the AST benchmark while the tokenizer is fine. I don't really understand why this is happening since the small unit tests are succeeding and the regex is basically the same.
Could you take a look for me?

**Comment by tversteeg** [comment]
I've benchmarked a bunch of stuff with [flame](https://github.com/llogiq/flame), and it seems that even though the nom optimizations improve the performance a lot with parsing the tokens, it doesn't help much at all with the creation of the AST which took 95% of the time when parsing `t.lua` or `date.lua`.

**Comment by Kampfkarren** [comment]
That would make sense, tokenization and AST creation are completely separate. I have to use some weird setup in order to profile since I'm on Windows (can't use flame), but I can take a look into that when I can.

**Comment by tversteeg** [comment]
I actually did use flame on Windows, I used it in combination with flamer, made an example project and added `#[flamer: :flame]` attributes to functions.

**Comment by Kampfkarren** [comment]
Weird, maybe it's WSL that I couldn't use it with.

**Comment by Kampfkarren** [comment]
Thinking on this more, I bet it's because we clone around `Arc`s everywhere during AST parsing phase. Every time I've tried to move everything to `Rc`, it ends up being a massive headache and I can never completely finish it whilst keeping things like `TokenReference` thread safe.

**Comment by tversteeg** [comment]
Wouldn't it be possible to have a reference to a single `String` like I mentioned before and when you add additional data structures they reference a different `String`? Reference-counting the data seems a bit awkward.

**Comment by Kampfkarren** [comment]
That's not really the issue, what's passed around is an `Arc<Arena<Token>>`, which refers to all the tokens parsed through tokenization.

**Comment by tversteeg** [comment]
Oh in that case I don't really understand the issue, it's because you clone the `Arc`'s? Why is that?

**Comment by Kampfkarren** [comment]
ParserState is generated and passed around a lot so it's easy to backtrace, you just throw out the ones you've made. Later, when working on mutation after all that code was written, we needed to add the Arena of tokens (as opposed to what was just a reference before) to comply with the new signatures of everything. 

The changes happened here: https://github.com/Kampfkarren/full-moon/commit/6bdecc2ab55940e94c54fe3ce849514bbfd756ac

**Comment by Kampfkarren** [comment]
I believe we've mostly solved this by now?
