### ISSUE TITLE
Replace AST parsing with nom

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/full-moon#53]
Nom, I believe, can handle both AST and parsing within one step. It might be worth removing our AST parser in favor of just using Nom. Possibly fixes #49.

**Comment by tongpipi** [comment]
![image](https://user-images.githubusercontent.com/49895714/72673699-49302f00-3aa9-11ea-9a35-622a83c89bbe.png)
selene-lib 0.4  cargo build  fail

**Comment by Kampfkarren** [comment]
@tongpipi Not the right repo, but this will be fixed soon.

**Comment by zhiburt** [comment]
Is this still relevant?

After #154

**Comment by Kampfkarren** [comment]
Probably not in this form, though I do want AST/parsing to be one step at some point still, I think.
