### ISSUE TITLE
Comment followed by a tab is a parse error

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/full-moon#55]

**Comment by Kampfkarren** [comment]
`--reloadCancelled[TAB]= true` also seems to fail.

**Comment by Kampfkarren** [comment]
Seems a tab anywhere in the comment fails.

I bet it's because the line for parsing comments uses [is_ascii_control](https://doc.rust-lang.org/std/primitive.char.html#method.is_ascii_control):

https://github.com/Kampfkarren/full-moon/blob/master/src/tokenizer.rs#L552

And `'\t'.is_ascii_control()` returns true. CC @tversteeg, any reason you used `is_ascii_control` instead of checking for `\n`?

**Comment by tversteeg** [comment]
Because it checked for all line endings type but also the end-of-file symbol. I didn't know it would also trigger on tabs though..

**Comment by Kampfkarren** [comment]
I switched it to what Lua does internally, which is just check for `\r` and `\n`.
