### ISSUE TITLE
Support continue in Roblox feature flag

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/full-moon#59]
`continue` is context specific, meaning this code is valid:

```lua
local continue = 3
print(continue)

for _ = 1, 2 do
    continue
end
```

**Comment by Klicer** [comment]
Is this ever going to be implemented? or do I have to put my code inside ugly if statements instead of using guard clauses?

**Comment by Kampfkarren** [comment]
My projects move with me--I haven't had a need to use continue yet, and nobody has tried to make a PR yet. This repository is open to contributions, however.

**Comment by brianush1** [comment]
This issue should be closed since https://github.com/Kampfkarren/full-moon/pull/76 was merged.
