### ISSUE TITLE
Allow omitting an integer part of 0 in number literals

### ISSUE THREAD

**Issue by Xiphoseer** [Kampfkarren/full-moon#63]
The lua5.1 implementation allows numbers literals like `.5` and even `.5e0` to represent a value of `0.5`. The `full-moon` tokenizer currently does not support this and it's not mentioned in the spec that this should work.

I'd like to use `full-moon` for an existing codebase which uses this a lot and would appreciate to know whether you could consider implementing this or accept a pull-request for it.

**Comment by Kampfkarren** [comment]
This is something that worked on the old parser, but doesn't anymore just because I forgot to put it in. I'm totally accepting of a PR for it.

**Comment by Xiphoseer** [comment]
Opened PR #65 for this and another change.
