### ISSUE TITLE
Needs precedence rules

### ISSUE THREAD

**Issue by Rerumu** [Kampfkarren/full-moon#64]
Precedence rules are missing for operators.
Example:
```Lua
local a = 1 == 1 and 0
```
Is parsed as
```Lua
local a = 1 == (1 and 0)
```
and expected behavior is
```Lua
local a = (1 == 1) and 0
```

**Comment by notzortex** [comment]
Has there been any progress to this? I'm assuming not since the entire git hasn't been too active recently, and this is a pretty deciding factor for me.

**Comment by Kampfkarren** [comment]
My projects move with me, and I haven't had a need for this yet. Until I do, I personally am probably not going to contribute any work towards it, but will be open for any contribution that does.
