### ISSUE TITLE
Parsing Errors with complex emojis (UTF-8 with Fitzpatrick modifiers)

### ISSUE THREAD

**Issue by SigmaThetaTech** [Kampfkarren/full-moon#80]
To reproduce:
Just enter a comment in bracket format (prefix --[[ ]]) with an emoji that has skin color. Examples:
--[[👨🏾‍💻]]
--[[🤴]]
--[[🧓🏽]]

The line after it will have a parse error. Actually, upon further testing, it throws even more errors, including saying that local variables were not local. 

![image](https://user-images.githubusercontent.com/59387280/87236320-bfe51f80-c39c-11ea-9fed-8d47f75eed28.png)

**Comment by Kampfkarren** [comment]
Does this happen if the complex emoji is in a string?

**Comment by SigmaThetaTech** [comment]
> Does this happen if the complex emoji is in a string, or anything other than a block comment?

I noticed that it only happened when you put the emoji in a block comment. Otherwise, commented normally, this doesn't seem to happen

**Comment by Kampfkarren** [comment]
https://github.com/Kampfkarren/full-moon/blob/master/full-moon/src/tokenizer.rs#L663-L672

My bet is because we're using `len()` (length of the text in bytes) instead of `chars().count()` (length of the text in readable characters) like we do elsewhere. This should be easy to write a test for.

**Comment by SigmaThetaTech** [comment]
> https://github.com/Kampfkarren/full-moon/blob/master/full-moon/src/tokenizer.rs#L663-L672
> 
> My bet is because we're using `len()` (length of the text in bytes) instead of `chars().count()` (length of the text in readable characters) like we do elsewhere. This should be easy to write a test for.

Hmmm! Yeah! I had a similar issue when I was doing some parsing experiments with string.match on some emojis:
![image](https://user-images.githubusercontent.com/59387280/87264187-36088580-c474-11ea-82af-9346de16678f.png)
I found that an emoji like the one above was actually 4 characters long rather than 1. I ended up using Roblox's string:split() and avoided having to count characters altogether, but I thought this was worth a mention.
