### ISSUE TITLE
Typed Lua - Tuple syntax is not supported

### ISSUE THREAD

**Issue by Kampfkarren** [Kampfkarren/full-moon#91]
```lua
function foo(): (number, number)
```

...produces a syntax error.

**Comment by JohnnyMorganz** [comment]
From what I can tell, I believe the original issue here is actually already resolved?
Although, I think there has been an unwanted side effect for it
```lua
function foo(x: (number, number)): string
```
is parsed as valid, however tuples can only be used as a **return type** for a function, I don't think they can be used anywhere else
