### ISSUE TITLE
Add support for labels/goto

### ISSUE THREAD

**Issue by Dekkonot** [Kampfkarren/full-moon#92]
As per the discussion in issue https://github.com/Kampfkarren/selene/issues/154, support needs to be added for `goto`/`::label::` syntax, probably behind a `luajit` crate flag.

This is primarily for LuaJIT, but this is one of the major changes in Lua 5.2 (the other 'breaking' changes are empty statements and `break` being allowed anywhere in the block), so that's worth taking into consideration -- it would probably be trivial after this to support 5.2 entirely.

This issue is mostly meant for the sake of posterity, as the proposal was already accepted on the Selene repo, I just want a record of it here too.

**Comment by Kampfkarren** [comment]
I want to do something like #47 where Lua 5.2 support is both a compile time and runtime flag, meaning a codebase must specify whether or not they actually use this.
