### ISSUE TITLE
Can't build the crate without roblox feature

### ISSUE THREAD

**Issue by zummenix** [Kampfkarren/full-moon#93]
Not that I need it, just checking out the repo :)

**Comment by Kampfkarren** [comment]
Dang, could've sworn I fixed this. This is a good reminder to get better CI.

**Comment by zummenix** [comment]
> better CI

Will github actions suffice for now?

**Comment by Kampfkarren** [comment]
That was my idea, yeah. Just actions for running cargo test with and without the Roblox feature flag.

**Comment by zummenix** [comment]
Resolved in a8951c16cb0643897e50416b358274a32a74c7ee
